### PR TITLE
Revert "Show progress information on box download"

### PR DESCRIPTION
**Pull request by Conan-Kudo**
python-wget is a dead module and we should not depend on it.

This reverts commit 4227ebb9dac070326f7c61ce5aca6596a3b72ba3.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@schaefi I haven't merged this yet, because we should figure out what we want to replace this with...

But I've applied a variant of this patch downstream in Fedora: https://src.fedoraproject.org/rpms/kiwi-boxed-plugin/c/4b65617c815f44fb7c0f643b2626993d10ec35b6

**Comment by schaefi** [comment]
Hmm, ok. I think I should have done a better research.

The module is pretty handy to use and could be easily integrated. Other options are

* progressbar
* tqdm

Using those needs more code as they are only progress bars not downloaders. I have no problem coding this but I prefer the most simple solution... if upstream supported

Thoughts / Alternatives ?

**Comment by Conan-Kudo** [comment]
[`urlgrabber`](https://pypi.org/project/urlgrabber/) is progressbar+downloader and is not completely dead.

**Comment by schaefi** [comment]
I'm using the progressbar module now. Please review #40 

As there is already a requirement to the requests module I only replaced the wget requirement with progressbar.
The progressbar module seems to be maintained code and at least on suse I also see a package for it

**Comment by schaefi** [comment]
closing on behalf of #40

**Pull request closed without merging**
