### PR TITLE
Fixed reading of plugin config

### PR DESCRIPTION
**Pull request by schaefi**
The plugin config file contains the configuration of the box
files as we create it as a service for the users. It is not
meant to be edited by users in the first place. Therefore the
location in /etc is somewhat misleading. This commit moves
the basic box configuration to be part of the plugin source.
As also the box image descriptions are handled in this git
changes to the box setup and eventually to the plugin config
are now going together. As a possitive side effect this also
fixes the installation of the plugin from pip which did
not properly handle the custom install routine for the config
file when it is hosted in /etc.

### CODE REVIEW

**Comment by schaefi** [comment]
Oh oh oh good point I forgot about setup.py... that needs adapting too, give me a second

**Comment by schaefi** [comment]
@davidcassany ok can you take another look ? Thanks

**Comment by schaefi** [comment]
well it was all based under the assumption that setup.py is always invoked by pip, so I tried to do the same we do in the .spec of the rpm to be also working on pip. But this is not possible due to the pip and wheel weirdness. So all of the convoluted approach can be deleted... with the given restrictions that via pip we can't handle the man pages.

For kiwi we should do the same but this will affect more files than just the man pages

**Comment by davidcassany** [comment]
> with the given restrictions that via pip we can't handle the man pages.

I am not sure this is actually the case. I agree that setuptools and wheel are weird at that, but I am quite convinced this can be done better, gained some setuptools experience recently. Moreover we were not even using setuptools, but distutils which is even older an trickier.

I'd like to give it a try on my spare time, I'll do some trials to see if I can manage to handle that nicer, ideally without changing RPM results and spec at all.

In KIWI I am afraid to touch this areas because as you say there are several files affected, and the use case matrix of pip, venv, rpm, etc. is not that simple to foresee.

**Comment by schaefi** [comment]
>I'd like to give it a try on my spare time, I'll do some trials to see if I can manage to handle that  nicer, ideally without changing RPM results and spec at all.

That would be nice. I don't consider myself an expert in setuptools and am happy if you find a way how we can gracefully handle all files through pip.

**Pull request merged**
